export const SET_IS_LOADING = "SET_IS_LOADING";
export const RESET_STATE = "RESET_STATE";
export const SET_STATUS_MESSAGE = "SET_STATUS_MESSAGE";
export const SET_FLOW_TREE = "SET_FLOW_TREE";
export const SET_AVAILABLE_NODES = "SET_AVAILABLE_NODES";
export const SET_JSON_EDITOR_CONTENT = "SET_JSON_EDITOR_CONTENT";